package one.direction;

import javafx.scene.media.MediaPlayer;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.io.File;
/**
 *
 * @author user
 */
public class finallyover extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public finallyover() {
     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
MediaPlayer mediaPlayer=null;
String fileNames=null;
int i=0;
String kbc=null;
String jb=null;
File jp=null;
            
            
            
            
            
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

       
        Statement n1=null;
        ResultSet b=null;
        String k1=null;
        String query="select * from currently_playing";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
            

           
            b=n1.executeQuery(query);
  while(b.next())       
  {k1=b.getString(1);
  }
      


 
b.close();
n1.close();
        
        }catch(Exception bla)
        {JOptionPane.showMessageDialog(null,"YOU HAVEN'T LOGIN");  }
        if(k1==null) 
             System.exit(0);
        else
            jLabel2.setText(k1);   
        
           
       ResultSet rst=null;
       Statement stmtt=null;
       try{
           Class.forName("com.mysql.jdbc.Driver");
Connection cont=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
  String ppt="select location from songs where sname='"+jLabel2.getText()+"';";            
stmtt=(Statement)cont.createStatement();
         rst=stmtt.executeQuery(ppt);
         
     rst.next();
           
            jLabel3.setText(rst.getString(1));
            
                 rst.close();
            stmtt.close();
        
           
           
       }catch(Exception t)
       {JOptionPane.showConfirmDialog(null,t.getMessage());}
     
             String kvpy="select * from songs;";
       ResultSet rstt=null;
       Statement stmttt=null;
       try{
           Class.forName("com.mysql.jdbc.Driver");
Connection contt=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");

           
stmttt=(Statement)contt.createStatement();
      rstt=stmttt.executeQuery(kvpy);   
          kvpy="UPDATE currently_playing SET LOCATION ='"+jLabel3.getText()+"' WHERE SONG ='"+jLabel2.getText()+"';";  
          stmttt.executeUpdate(kvpy);
          
          
   
           
           
       }catch(Exception tt)
       {JOptionPane.showConfirmDialog(null,tt.getMessage());}
       this.setVisible(false);
       new NewJFrame21().setVisible(true);
        
      
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         //  Statement a=null;
      //  ResultSet b=null;
       // String query="select * from id";
        
     //   try
      //  {
        //    Class.forName("com.mysql.jdbc.Driver");
       //     Connection c=(Connection)
          //  DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
          //  a=(Statement)c.createStatement();
         //   b=a.executeQuery(query);

    //    query="delete from currently_playing;";
        //    a.executeUpdate(query);
           //  query="INSERT INTO user (USERNAME) VALUES('"+(r)+"');";
          

      //  }catch (Exception ip)
      //  {JOptionPane.showMessageDialog(null,ip.getMessage()); }
//this.setVisible(false);  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
  // Statement a=null;
     //   ResultSet b=null;
     //   String query="select * from id";
     //   
     //   try
     //   {
      //      Class.forName("com.mysql.jdbc.Driver");
      //      Connection c=(Connection)
       //     DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
        //    a=(Statement)c.createStatement();
         //   b=a.executeQuery(query);

      //  query="delete from currently_playing;";
    //        a.executeUpdate(query);
           //  query="INSERT INTO user (USERNAME) VALUES('"+(r)+"');";
          

     //   }catch (Exception ip)
     //   {JOptionPane.showMessageDialog(null,ip.getMessage()); }
//this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finallyover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finallyover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finallyover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finallyover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finallyover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
