package one.direction;

import com.sun.glass.events.KeyEvent;
import javax.swing.JColorChooser;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.IOException;
import java.awt.Image;
/**
 *
 * @author user
 */
public class new_account extends javax.swing.JFrame {
     

    /**
     * Creates new form NewJFrame
     */
    public new_account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hi = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bye = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        hi.setForeground(new java.awt.Color(255, 255, 255));
        hi.setLayout(null);

        jButton1.setText("new user");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        hi.add(jButton1);
        jButton1.setBounds(40, 140, 170, 100);

        jButton2.setText("login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        hi.add(jButton2);
        jButton2.setBounds(250, 150, 210, 90);

        jButton3.setText("change background ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        hi.add(jButton3);
        jButton3.setBounds(50, 270, 170, 80);

        jButton4.setText("FORGOT PASSWORD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        hi.add(jButton4);
        jButton4.setBounds(150, 380, 220, 80);

        jButton5.setText("set background");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        hi.add(jButton5);
        jButton5.setBounds(240, 270, 210, 90);

        bye.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                byeMouseMoved(evt);
            }
        });
        hi.add(bye);
        bye.setBounds(0, 0, 500, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hi, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hi, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 MediaPlayer mediaPlayer ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  Statement a=null;
        ResultSet b=null;
        String query="select * from id";
        JTextField username=new JTextField();
        JTextField password=new JPasswordField();
             JLabel kbc=new JLabel();
        if(Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) 
kbc.setText("CAPSLOCK is ON");
else
            kbc.setText("CAPSLOCK is OFF"); 
        JOptionPane.showConfirmDialog(null,"your "+kbc.getText()+" do you want to continue????????......");
             if(Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) 
kbc.setText("CAPSLOCK is ON");
else
            kbc.setText("CAPSLOCK is OFF"); 
        Object[] message={
            "USERNAME",username,"PASSWORD",password,"capslock status",kbc
        };
        JOptionPane.showConfirmDialog(null,message,"login",JOptionPane.OK_CANCEL_OPTION);
        String k=password.getText();

        String r=username.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            a=(Statement)c.createStatement();
            b=a.executeQuery(query);

            query="INSERT INTO ID (USERNAME,PASSWORD) VALUES('"+(r)+"','"+(k)+"');";
            a.executeUpdate(query);
             query="INSERT INTO user (USERNAME) VALUES('"+(r)+"');";
            a.executeUpdate(query);
        

        }catch (Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage()); }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
   Statement a=null;
        ResultSet b=null;
        JTextField password=new JPasswordField();
        String query="select * from id";
        JTextField username=new JTextField();
      
         JLabel kbc=new JLabel();
        
            if(Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) 
kbc.setText("CAPSLOCK is ON");
else
           kbc.setText("CAPSLOCK is OFF"); 
             JOptionPane.showConfirmDialog(null,"your "+kbc.getText()+" do you want to continue????????......");
           if(Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) 

               kbc.setText("CAPSLOCK is ON");
else
           {      kbc.setText("CAPSLOCK is OFF");}
          Object[] message={
            "USERNAME",username,"PASSWORD",password,"capslock status",kbc
        };
        JOptionPane.showConfirmDialog(null,message,"login",JOptionPane.OK_CANCEL_OPTION);
        String k=password.getText();

        String r=username.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            a=(Statement)c.createStatement();
            

            query="Select * from id";
            b=a.executeQuery(query);
          
while(b.next())

{String f1=b.getString(1);
String f2=b.getString(2);
if(r.equals(f1))
{
if(f2.equals(k))
         query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
            a.executeUpdate(query);
this.setVisible(false);
mediaPlayer.stop();
new NewJFrame1().setVisible(true);
break;}
}


 
b.close();
a.close();
        
        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,"no id found");  }
        
      



// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  JColorChooser abc=new JColorChooser();
  Object[] me={
  "choose colour",abc
  };
  JOptionPane.showConfirmDialog(this,me);
  bye.setIcon(null);
  hi.setBackground(abc.getColor());
  

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void byeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byeMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_byeMouseMoved

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  Statement a=null;
   Statement ab=null;
        ResultSet b=null;
         ResultSet bb=null;
        ResultSet kk=null;
        JTextField password=new JTextField();
        String query="select * from id";
        JTextField username=new JTextField();
     
        JTextField p=new JTextField();
         JLabel kbc=new JLabel();
        
            if(Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) 
kbc.setText("CAPSLOCK is ON");
else
           kbc.setText("CAPSLOCK is OFF"); 
             JOptionPane.showConfirmDialog(null,"your "+kbc.getText()+" do you want to continue????????......");
           if(Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK)) 

               kbc.setText("CAPSLOCK is ON");
else
           {      kbc.setText("CAPSLOCK is OFF");}
          Object[] message={
            "USERNAME",username,"NATIONALITY",password,"FAVOURITE SINGER",p,"capslock status",kbc
        };
        JOptionPane.showConfirmDialog(null,message,"login",JOptionPane.OK_CANCEL_OPTION);
        String k=password.getText();
 String s=p.getText();
        String r=username.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
             Connection cb=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            a=(Statement)c.createStatement();
             ab=(Statement)cb.createStatement();

            query="Select * from user";
            b=a.executeQuery(query);
          
while(b.next())

{String f1=b.getString(1);
String f2=b.getString(2);
String f5=b.getString(5);

if(r.equals(f1))
{
if(f2.equals(k))
{if (f5.equals(s))     
    query="Select (PASSWORD) from id where USERNAME='"+f1+"';";
bb=ab.executeQuery(query);
bb.next();
String fa1=bb.getString(1);
  
 JOptionPane.showMessageDialog(null,"sorry for inconvenience cause master "+f1+" your password is "+fa1+"");
    break;
    
    
    }  


}
}


 
b.close();
a.close();
        
        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,"no id found");  }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    Statement n1=null;
        ResultSet b=null;
        String k1=null;
        String query="select * from login";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
            

           
            b=n1.executeQuery(query);
  b.next();        
k1=b.getString(1);

      


 
b.close();
n1.close();
        
        }catch(Exception i)
        {  }
        if(k1==null)
             
        {    
        
String fileNames=null;
 //final CountDownLatch latch = new CountDownLatch(1);
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new JFXPanel(); // initializes JavaFX environment
                //latch.countDown();
            }
        });
   //     try {
     //       latch.await();
      //  } catch (InterruptedException ex) {
       //     Logger.getLogger(new_account.class.getName()).log(Level.SEVERE, null, ex);
        //}
JFileChooser choosers = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "MP3 Files", "mp3");
    choosers.setFileFilter(filter);
    choosers.setCurrentDirectory(new File("F:/music"));
    int returnVal = choosers.showOpenDialog(null);
    if(returnVal == JFileChooser.APPROVE_OPTION) {
       fileNames=     choosers.getSelectedFile().toURI().toString();
    }
 mediaPlayer = new MediaPlayer(new Media(fileNames));

   
   mediaPlayer.play();
   mediaPlayer.onRepeatProperty();

      }
        else {this.setVisible(false);
        new NewJFrame1().setVisible(true);
        }
       
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
JFileChooser chooser = new JFileChooser();
       File F = new File("F:/music");
  //    File namedir;
      File namepath;
      FileNameExtensionFilter k=new FileNameExtensionFilter("jpg files", "jpg");
chooser.setFileFilter(k);
      chooser.setCurrentDirectory(F);
      chooser.showOpenDialog(null);
      chooser.setDialogTitle("Choose file to play");
       chooser.setApproveButtonText("Play");
 // namedir = chooser.getCurrentDirectory();
  namepath = chooser.getSelectedFile();
 //System.out.print("the name of the the directory is "+namedir.getName());
  //System.out.print("the name of the the path is "+namepath.getAbsolutePath());
  String fileName=namepath.getAbsolutePath();
  BufferedImage img = null;
try {
    img = ImageIO.read(new File(fileName));
} catch (IOException e) {
 JOptionPane.showConfirmDialog(this, e.getMessage());  // e.printStackTrace();
}
Image dimg = img.getScaledInstance(bye.getWidth(), bye.getHeight(),
        Image.SCALE_SMOOTH);
   ImageIcon icon=new ImageIcon(dimg) ;
   
  bye.setIcon(icon);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bye;
    private javax.swing.JPanel hi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
