package one.direction;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author user    
*/
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        a = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setText("nationality");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 106, 28);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE ONE AMONG THE BELOW CONTENTS", "indian", "non-indian" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(160, 40, 310, 50);
        jPanel1.add(a);
        a.setBounds(10, 0, 170, 31);

        jLabel2.setText("language of music you prefer");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 110, 200, 32);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select the requirement below", "hindi", "english" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(230, 100, 220, 50);

        jLabel3.setText("type of music you prefer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 160, 165, 34);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select among below options", "POP", "Folk", "Dance" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(230, 160, 230, 40);

        jLabel4.setText("Choose your favourate singer ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 210, 180, 60);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select one among below" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(250, 200, 210, 50);

        jButton1.setText("return back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 280, 121, 36);

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 280, 112, 40);

        jButton5.setText("ADD MORE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(200, 280, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        String j=null;
String l=null;
switch(jComboBox1.getSelectedIndex())
{ case 0: 
     jButton5.setVisible(false);
    jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
case 1:
case 2:
switch(jComboBox2.getSelectedIndex())
{ case 0: 
     jButton5.setVisible(false);
    jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
    case 1:
        j="hindi"; 
   switch(jComboBox3.getSelectedIndex())
   {case 0:  jButton5.setVisible(false);
   jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
       case 1:l="POP";  jButton5.setVisible(true);
       jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 2:l="Folk";  jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 3:l="Dance"; jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
       }break;
    case 2: j="english";
    switch(jComboBox3.getSelectedIndex())
   {case 0:
        jButton5.setVisible(false);
       jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
   case 1:l="POP";
    jButton5.setVisible(true);
   jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 2:l="Folk"; 
 jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 3:l="Dance";
 jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
       }break;
    }        
          Statement t=null;
        ResultSet b=null;
        String query="select * from singers";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            t=(Statement)c.createStatement();
            

            query="Select name from singers where type='"+l+"' && language='"+j+"';";
            b=t.executeQuery(query);
          jComboBox4.removeAllItems();
while(b.next())

{String f1=b.getString(1);
jComboBox4.addItem(f1);
//if(r.equals(f1))
//{
//if(f2.equals(k))
         //query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
        //    t.executeUpdate(query);
//this.setVisible(false);
//new NewJFrame1().setVisible(true);
//break;}
}


 
b.close();
t.close();
        
        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage());  }
    }
        
        
        
        String k=null;
        switch(jComboBox1.getSelectedIndex())
{case 1:k="indian";break;
case 2:k="non-indian";break;
    }
        Statement n=null;
       String k1=null;
        ResultSet b=null;
        String query="select * from login";
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n=(Statement)c.createStatement();
            b=n.executeQuery(query);
             b.next();        
k1=b.getString(1);

           query="UPDATE user set nationality ='"+k+"'where username ='"+k1+"';";
            n.executeUpdate(query);
     
        

        }catch (Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage()); } 


// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 Statement n1=null;
        ResultSet b=null;
         String k1=null;
        String query="select * from login";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
  b=n1.executeQuery(query);
  b.next();        
k1=b.getString(1);
 query="Delete from login where username ='"+k1+"';";
 n1.executeUpdate(query);
      }catch (Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage()); }  
this.setVisible(false);        
new new_account().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
 Statement n1=null;
        ResultSet b=null;
        String k1=null;
        String k2=null;
        String k3=null;
        String k4=null;
        String k5=null;
        
        String query="select * from user";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
            

           
            b=n1.executeQuery(query);
  while(b.next())        
  {k1=b.getString(1);
  k2=b.getString(2);
  k3=b.getString(3);
  k4=b.getString(4);
k5=b.getString(5);
      


  }
b.close();
n1.close();
        
        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,"YOU HAVEN'T LOGIN");  }
        if(k1==null || k2==null || k3==null || k4==null || k5==null) 
        {}  
        else
        {  this.setVisible(false); 
        new ultimate().setVisible(true);}// TODO add your handling code here:
                // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
String j=null;
String l=null;
switch(jComboBox1.getSelectedIndex())
{ case 0:
     jButton5.setVisible(false);
    jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
case 1:
case 2:
switch(jComboBox2.getSelectedIndex())
{ case 0: 
     jButton5.setVisible(false);
    jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
    case 1:
        j="hindi"; 
   switch(jComboBox3.getSelectedIndex())
   { case 0: 
       
         jButton5.setVisible(false);
       jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
   case 1:l="POP";
     jButton5.setVisible(true);
   jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 2:l="Folk"; 
jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 3:l="Dance"; 
jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
       }break;
    case 2: j="english";
    switch(jComboBox3.getSelectedIndex())
   { case 0: 
       jButton5.setVisible(false);
       jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
   case 1:
l="POP"; 

jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 2:l="Folk";
jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 3:l="Dance"; 
jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
       }break;
    }        
          Statement t=null;
        ResultSet b=null;
        String query="select * from singers";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            t=(Statement)c.createStatement();
            

            query="Select name from singers where type='"+l+"' && language='"+j+"';";
            b=t.executeQuery(query);
          jComboBox4.removeAllItems();
while(b.next())

{String f1=b.getString(1);
jComboBox4.addItem(f1);
//if(r.equals(f1))
//{
//if(f2.equals(k))
         //query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
        //    t.executeUpdate(query);
//this.setVisible(false);
//new NewJFrame1().setVisible(true);
//break;}
}


 
b.close();
t.close();
        
        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage());  }
    }
        String k=null;
        switch(jComboBox1.getSelectedIndex())
{ case 0: 
    jButton5.setVisible(false);
    jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
case 1:k="hindi";


case 2:k="english";break;

    }
        Statement n=null;
       String k1=null;
        ResultSet bt=null;
        String querys="select * from login";
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n=(Statement)c.createStatement();
            bt=n.executeQuery(querys);
             bt.next();        
k1=bt.getString(1);

           querys="UPDATE user set mlang ='"+(k)+"'where username ='"+k1+"';";
            n.executeUpdate(querys);
     
        

        }catch (Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage()); } // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
String j=null;
String l=null;
switch(jComboBox1.getSelectedIndex())
{ case 0: 
    jButton5.setVisible(false);
    jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
    case 1:
    
case 2:
        switch(jComboBox2.getSelectedIndex()){ case 0: 
            jButton5.setVisible(false);
            jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
    case 1:
        j="hindi"; 
   switch(jComboBox3.getSelectedIndex())
   { case 0: 
           jButton5.setVisible(false);
       jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
   case 1:l="POP";
       jButton5.setVisible(true);
   jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 2:l="Folk";
  jButton5.setVisible(true);
  jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 3:l="Dance";
  jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
       }break;
    case 2: j="english";
    switch(jComboBox3.getSelectedIndex())
   { case 0: 
         jButton5.setVisible(false);
       jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
   case 1:l="POP";
     jButton5.setVisible(true);
   jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 2:l="Folk";
  jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
case 3:l="Dance";
  jButton5.setVisible(true);
jComboBox4.setVisible(true);
jLabel4.setVisible(true);break;
       }break;
    }        
          Statement t=null;
        ResultSet b=null;
        String query="select * from singers";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            t=(Statement)c.createStatement();
            

            query="Select name from singers where type='"+l+"' && language='"+j+"';";
            b=t.executeQuery(query);
          jComboBox4.removeAllItems();
          jComboBox4.addItem("please select one among below");
while(b.next())

{String f1=b.getString(1);
jComboBox4.addItem(f1);
//if(r.equals(f1))
//{
//if(f2.equals(k))
         //query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
        //    t.executeUpdate(query);
//this.setVisible(false);
//new NewJFrame1().setVisible(true);
//break;}
}


 
b.close();
t.close();
        
        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage());  }
    }

        
        
        
        String k=null;
        switch(jComboBox1.getSelectedIndex())
{ case 0:
    jButton5.setVisible(false);
    jComboBox4.setVisible(false);
jLabel4.setVisible(false);break;
            case 1:k="POP";break;
case 2:k="Folk";break;
case 3:k="Dance";break;

    }
        Statement n=null;
       String k1=null;
        ResultSet bt=null;
        String querys="select * from login";
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n=(Statement)c.createStatement();
            bt=n.executeQuery(querys);
             bt.next();        
k1=bt.getString(1);

           querys="UPDATE user set mtype ='"+(k)+"'where username ='"+k1+"';";
            n.executeUpdate(querys);
     
        

        }catch (Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage()); } 


// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
     
        
        
   // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           String kx=jComboBox4.getSelectedItem().toString();
       
      
        Statement n=null;
       String k1=null;
        ResultSet b=null;
        String query="select * from login";
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n=(Statement)c.createStatement();
            b=n.executeQuery(query);
             b.next();        
k1=b.getString(1);

           query="UPDATE user set fav_singer ='"+kx+"'where username ='"+k1+"';";
            n.executeUpdate(query);
     //
           //System.err.println(kx);

        }catch (Exception i)
        {JOptionPane.showMessageDialog(null,i.getMessage()); } 
         
        this.setVisible(false);
        new ultimate().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Statement t=null;
        ResultSet b=null;
        JComboBox kb=new JComboBox();
        int i=0;
        int k=jComboBox2.getItemCount()-1;
        while(k>=i)
        {   kb.addItem(jComboBox2.getItemAt(i));
        ++i;
        }
  JComboBox kcb=new JComboBox();
        int ic=0;
        int kc=jComboBox3.getItemCount()-1;
        while(kc>=ic)
        {   kcb.addItem(jComboBox3.getItemAt(ic));
        ++ic;}
        String query="select * from singers";
        JTextField singer=new JTextField();
      //  JTextField language=new JTextField();
      //  JTextField type=new JTextField();
           
       // Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK); 
Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, true);
        
        Object[] messageS={
            "SINGER NAME",singer,"LANGUAGE",kb,"TYPE",kcb
        };
        JOptionPane.showConfirmDialog(null,messageS,"add more , more fun",JOptionPane.OK_CANCEL_OPTION);
       String kk=kb.getSelectedItem().toString();
 String qw=kcb.getSelectedItem().toString();

        String r=singer.getText();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            t=(Statement)c.createStatement();
            b=t.executeQuery(query);

            query="INSERT INTO singers (name,language,type) VALUES('"+(r)+"','"+(kk)+"','"+qw+"');";
            t.executeUpdate(query);
             
        

        }catch (Exception ik)
        {JOptionPane.showMessageDialog(null,ik.getMessage()); }  
        jComboBox4.addItem(r);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 jButton5.setVisible(false);
        jLabel4.setVisible(false);
        jComboBox4.setVisible(false);
        Statement n1=null;
        ResultSet b=null;
        String k1=null;
        String query="select * from login";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
            

           
            b=n1.executeQuery(query);
  b.next();        
k1=b.getString(1);

      


 
b.close();
n1.close();
        
        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,"YOU HAVEN'T LOGIN");  }
        if(k1==null) 
             System.exit(0);
        else
            a.setText("hello "+k1);         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
