package one.direction;

import javax.swing.*;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javax.swing.SwingUtilities;
import java.util.Timer;
import java.util.TimerTask;
import javafx.util.Duration;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.geometry.HPos;
import javafx.geometry.Insets;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.effect.DropShadow;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import javafx.scene.media.MediaView;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class NewJFrame2111 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public NewJFrame2111() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 255));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton13.setText("jButton13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(180, 180, 79, 23);

        jButton1.setText("play");
        jButton1.setMaximumSize(new java.awt.Dimension(101, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(101, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 290, 53, 23);

        jButton2.setText("stop");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 290, 53, 23);

        jButton3.setText("pause");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 290, 70, 23);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 180, 379, 40);

        jButton4.setText("play");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(110, 290, 53, 23);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 230, 110, 40);

        jButton7.setText("volume down");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(390, 320, 120, 30);

        jButton6.setText("mute");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(410, 290, 90, 23);

        jButton5.setText("volume up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(410, 260, 90, 23);

        jButton8.setText("set audio at");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(280, 240, 100, 23);

        jButton9.setText("unmute");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(410, 290, 90, 23);

        jButton10.setText("volume up");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(410, 260, 90, 23);

        jButton11.setText("volume down");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(390, 320, 120, 30);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 150, 140, 30);

        jButton12.setText("close");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(170, 350, 110, 23);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel3.setText("AUDIO PLAYER ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 10, 390, 50);

        jLabel4.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel4.setText("PRESS PLAY TO START ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 50, 560, 50);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        jLabel5.setText("THE SELECTED SONG");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 90, 530, 50);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 270, 60, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents
MediaPlayer mediaPlayer;
String k1=null;
double y;
double r;
JTextField j=  new JTextField();
 String jb;
 Stage st=new Stage();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
{  {
  
  
 try{  SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new JFXPanel();

         }
        });
   new JFXPanel();
        mediaPlayer = new MediaPlayer(new Media(jb));

     mediaPlayer.play();

     
       
             jLabel2.setText(k1);
            


Timer timer = new Timer();
TimerTask myTask = new TimerTask() {
    @Override
    public void run() {
               double d=mediaPlayer.getCycleDuration().toSeconds();
        double z=mediaPlayer.getCurrentTime().toSeconds();
int e=  (int) (d*100);
double r=e/100;
int t=  (int) (z*100);
double y=t/100;

     jLabel1.setText("total duration="+y+"sec/"+r+"sec");    // whatever you need to do every 2 seconds
    }
};

timer.schedule(myTask, 1000, 1000);

     mediaPlayer.play();





jButton1.setVisible(false);

                      
 }catch(Exception t)
 {JOptionPane.showMessageDialog(this, t.getMessage());}
}}               
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
mediaPlayer.stop();
y=00;
r=00;
jLabel1.setText("total duration="+y+"sec/"+r+"sec");
jLabel2.setText("");
       // this.setVisible(false);
//new ultimate().setVisible(true);
     


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
 
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
mediaPlayer.pause(); 
jButton1.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  mediaPlayer.play();     
//jButton1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
double i=100;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  i=i+10;
mediaPlayer.setVolume(i);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

mediaPlayer.setMute(true);
jButton6.setVisible(false);
jButton5.setVisible(false);
jButton7.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
i=i-10;
mediaPlayer.setVolume(i);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    int g=Integer.parseInt(jTextField1.getText());
        mediaPlayer.seek(Duration.seconds(g));
    


// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
mediaPlayer.setMute(false);  
jButton6.setVisible(true);
jButton5.setVisible(true);
jButton7.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        mediaPlayer.setMute(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        mediaPlayer.setMute(false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed
String fileNames;
String kk;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

   

        jb = kjp();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 Statement n1=null;
        ResultSet b=null;
      
        String query="select * from login";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
  b=n1.executeQuery(query);
     

 query="Delete from currently_Playing where song ='"+jLabel2.getText()+"';";
 n1.executeUpdate(query);
      }catch (Exception ij)
        {JOptionPane.showMessageDialog(null,ij.getMessage()); }  
this.setVisible(false);        
new ultimate().setVisible(true);  
mediaPlayer.stop();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       Statement n1=null;
        ResultSet b=null;
      
        String query="select * from login";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
  b=n1.executeQuery(query);
     

 query="Delete from currently_Playing where song ='"+jLabel2.getText()+"';";
 n1.executeUpdate(query);
      }catch (Exception ij)
        {JOptionPane.showMessageDialog(null,ij.getMessage()); }  
this.setVisible(false);        
new ultimate().setVisible(true);  
mediaPlayer.stop();   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
Statement n1=null;
        ResultSet b=null;
      
        String query="select * from login";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
  b=n1.executeQuery(query);
     

 query="Delete from currently_Playing where song ='"+jLabel2.getText()+"';";
 n1.executeUpdate(query);
      }catch (Exception ij)
        {JOptionPane.showMessageDialog(null,ij.getMessage()); }  
this.setVisible(false);        
new ultimate().setVisible(true);  
mediaPlayer.stop();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    JOptionPane.showConfirmDialog(this, st);
  SwingUtilities.invokeLater(JFXPanel::new);
   
   JFileChooser chooser = new JFileChooser();
        
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileNames = chooser.getSelectedFile().toURI().toString();
           
        }//   Statement n1=null;
     //   ResultSet b=null;
     //  fileNames=null;
    //    String query="select * from currently_playing";
    
   //     try
   //     {
   //         Class.forName("com.mysql.jdbc.Driver");
     //       Connection c=(Connection)
      //      DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
      //      n1=(Statement)c.createStatement();
      //      
      //     
      //      b=n1.executeQuery(query);
//  while(b.next())       
//  {kk=b.getString(1);
// fileNames=b.getString(2);
 //
 // }

        
       // }catch(Exception bla)
      //  {JOptionPane.showMessageDialog(null,bla.getMessage());  }
    MediaPlayer mediaPlayer;

      
    new JFXPanel();
     mediaPlayer = new MediaPlayer(new Media(fileNames));
mediaPlayer.play();
new JFXPanel();
        // Create a 400X300 MediaView
        MediaView mediaView = new MediaView(mediaPlayer);

        mediaView.setFitWidth(400);
        mediaView.setFitHeight(300);
        mediaView.setSmooth(true);
        mediaView.setLayoutX(200);
        mediaView.setLayoutY(200);
        // Create the DropShadow effect
        DropShadow dropshadow = new DropShadow();
        dropshadow.setOffsetY(5.0);
        dropshadow.setOffsetX(5.0);
        dropshadow.setColor(Color.RED);

        mediaView.setEffect(dropshadow);

        Rectangle rect4 = new Rectangle(35, 55, 95, 25);
        rect4.setFill(Color.RED);
        rect4.setStroke(Color.BLACK);
        rect4.setStrokeWidth(1);

        // Create the HBox
        // HBox controlBox = new HBox(5, null, null);

        // Create the VBox
        VBox root = new VBox(1, mediaView);

        GridPane gridpane = new GridPane();
        gridpane.setPadding(new Insets(95));
        gridpane.setHgap(1);
        gridpane.setVgap(10);

        GridPane.setHalignment(rect4, HPos.CENTER);

        Group grp = new Group();
        gridpane.add(root, 1, 1);

        grp.getChildren().add(gridpane);

        // Create the Scene
        Scene scene = new Scene(grp);

        // Add the scene to the Stage
        st.setScene(scene);
        // Set the title of the Stage
        st.setTitle("A simple Media Example");
        // Display the Stage
        st.show();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame2111().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private String kjp() {
         Statement n1=null;
        ResultSet b=null;
        String fileNames=null;
        String query="select * from currently_playing";
    
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();
            
           
            b=n1.executeQuery(query);
  while(b.next())       
  {k1=b.getString(1);
 fileNames=b.getString(2);
 
  }


            //JFileChooser choosers = new JFileChooser();
           // FileNameExtensionFilter filter = new FileNameExtensionFilter(
     // "MP3 Files", "mp3");
   // choosers.setFileFilter(filter);
  // choosers.setCurrentDirectory(new File (fileNames));
   // int returnVal = choosers.showOpenDialog(null);
   // if(returnVal == JFileChooser.APPROVE_OPTION) {
     //  fileNames=     choosers.getSelectedFile().toURI().toString();
   // }else{}
   
   
   



 
////b.close();
//n1.close();
        
        }catch(Exception bla)
        {JOptionPane.showMessageDialog(null,bla.getMessage());  }
        return fileNames;
    }
}
