package one.direction;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.Stage;
import  javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author user
 */
public class promo extends javax.swing.JFrame {

    /**
     * Creates new form promo
     */
    public promo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel2.setText("discover a new world");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 180, 690, 80);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setText("click here");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 60, 210, 60);

        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton1.setText("and");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 30, 690, 242);

        pack();
    }// </editor-fold>//GEN-END:initComponents
FileNameExtensionFilter f = null;
String KBB;
String j=null;
JLabel tt4=new JLabel();
String quake=null;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JButton a1=new JButton("explore songs");
        a1.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                JButton s=new JButton("FIND");
                JButton ss=new JButton("ADD");
                JButton sss=new JButton("LOGOUT");
            
                Object[] chios={
                    s,ss,sss

                };
            

                sss.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        Statement n1=null;
                        ResultSet b=null;
                        String k1=null;
                        String query="select * from login";

                        try
                        {
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection c=(Connection)
                            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                            n1=(Statement)c.createStatement();
                            b=n1.executeQuery(query);
                            b.next();
                            k1=b.getString(1);
                            query="Delete from login where username ='"+k1+"';";
                            n1.executeUpdate(query);
                        }catch (Exception i)
                        {JOptionPane.showMessageDialog(null,i.getMessage()); }

                        System.exit(0);

                    }
                });

                s.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                         JRadioButton rX=new JRadioButton("AUDIO");
                          JRadioButton rXX=new JRadioButton("VIDEO");
                        ButtonGroup bIg=new ButtonGroup();
                        bIg.add(rX);
                           bIg.add(rXX);
                           rX.setSelected(true);
                        JRadioButton r=new JRadioButton("name");
                        ButtonGroup bg=new ButtonGroup();
                        JButton kkkk=new JButton("search");
                        JRadioButton r1=new JRadioButton("type");
                        JRadioButton r2=new JRadioButton("language");
                        JRadioButton r3=new JRadioButton("singer name");
                        bg.add(r);
                        bg.add(r1);
                        bg.add(r2);
                        bg.add(r3);
                        JTextField tf=new JTextField();
                        Object[] nop={
                          rX,rXX,r,r1,r2,r3,"enter the choosen value",tf,kkkk
                        };
                        kkkk.addActionListener(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent ae) {
                                JButton kkq=new JButton("play");
                                JComboBox jComboBox4=new JComboBox();
                                Object [] kd={
                                    jComboBox4,kkq
                                };
                                String jaa = null;
                               if(rX.isSelected()){ if(r.isSelected())
                                {jaa="sname";
                                }else if (r1.isSelected()) {
                                    jaa="type";

                                }
                                else if (r2.isSelected()) {
                                    jaa="language";

                                }
                                else if (r3.isSelected()) {
                                    jaa="aname";

                                }

                                Statement t=null;
                                ResultSet b=null;
                                String query="select * from songs";
                                try
                                {
                                    Class.forName("com.mysql.jdbc.Driver");
                                    Connection c=(Connection)
                                    DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                                    t=(Statement)c.createStatement();

                                    query="Select sname from songs where "+jaa+"='"+tf.getText()+"';";
                                    b=t.executeQuery(query);
                                    jComboBox4.removeAllItems();
                                    jComboBox4.addItem("please select one among below");
                                    while(b.next())

                                    {String f1=b.getString(1);
                                        jComboBox4.addItem(f1);
                                        //if(r.equals(f1))
                                        //{
                                            //if(f2.equals(k))
                                            //query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
                                            //    t.executeUpdate(query);
                                            //this.setVisible(false);
                                            //new NewJFrame1().setVisible(true);
                                            //break;}
                                    }

                                    b.close();
                                    t.close();

                                }catch(Exception i)
                                {JOptionPane.showMessageDialog(null,i.getMessage());  }}
                               else if(rXX.isSelected()){ if(r.isSelected())
                                {jaa="sname";
                                }else if (r1.isSelected()) {
                                    jaa="type";

                                }
                                else if (r2.isSelected()) {
                                    jaa="language";

                                }
                                else if (r3.isSelected()) {
                                    jaa="aname";

                                }

                                Statement t=null;
                                ResultSet b=null;
                                String query="select * from songs";
                                try
                                {
                                    Class.forName("com.mysql.jdbc.Driver");
                                    Connection c=(Connection)
                                    DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                                    t=(Statement)c.createStatement();

                                    query="Select sname from VIDEO where "+jaa+"='"+tf.getText()+"';";
                                    b=t.executeQuery(query);
                                    jComboBox4.removeAllItems();
                                    jComboBox4.addItem("please select one among below");
                                    while(b.next())

                                    {String f1=b.getString(1);
                                        jComboBox4.addItem(f1);
                                        //if(r.equals(f1))
                                        //{
                                            //if(f2.equals(k))
                                            //query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
                                            //    t.executeUpdate(query);
                                            //this.setVisible(false);
                                            //new NewJFrame1().setVisible(true);
                                            //break;}
                                    }

                                    b.close();
                                    t.close();

                                }catch(Exception i)
                                {JOptionPane.showMessageDialog(null,i.getMessage());  }}

                                kkq.addActionListener(new ActionListener() {
                                    @Override
                                    public void actionPerformed(ActionEvent ae) {

                                        Statement a=null;
                                        ResultSet b=null;
                                        String query="select * from id";

                                        try
                                        {
                                            Class.forName("com.mysql.jdbc.Driver");
                                            Connection c=(Connection)
                                            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                                            a=(Statement)c.createStatement();
                                            b=a.executeQuery(query);

                                            query="INSERT INTO currently_playing (song) VALUES('"+(jComboBox4.getSelectedItem().toString())+"');";
                                            a.executeUpdate(query);

                                        }catch (Exception i)
                                        {JOptionPane.showMessageDialog(null,i.getMessage()); }
                                             
     
                                        if(rX.isSelected())
{
                        
                         quake="songs";
}
else if(rXX.isSelected())
{
        
         quake="video";
}
                                        ResultSet rst=null;
       Statement stmtt=null;
       try{
           Class.forName("com.mysql.jdbc.Driver");
Connection cont=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
  String ppt="select location from "+quake+" where sname='"+jComboBox4.getSelectedItem().toString()+"';";            
stmtt=(Statement)cont.createStatement();
         rst=stmtt.executeQuery(ppt);
         
     rst.next();
           
      KBB=rst.getString(1);
            
                 rst.close();
            stmtt.close();
        
           
           
       }catch(Exception t)
       {JOptionPane.showConfirmDialog(null,t.getMessage());}
          String kvpy="select * from songs;";
       ResultSet rstt=null;
       Statement stmttt=null;
       try{
           Class.forName("com.mysql.jdbc.Driver");
Connection contt=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");

           
stmttt=(Statement)contt.createStatement();
      rstt=stmttt.executeQuery(kvpy);   
          kvpy="UPDATE currently_playing SET LOCATION ='"+KBB+"' WHERE SONG ='"+jComboBox4.getSelectedItem().toString()+"';";  
          stmttt.executeUpdate(kvpy);
          
          
   
           
           
       }catch(Exception tt)
       {JOptionPane.showConfirmDialog(null,tt.getMessage());}
       dispose();
       {if(rX.isSelected())
       { new NewJFrame21().setVisible(true);}
       else{if(rXX.isSelected())
       {       
           try {
               Stage stages = null;
               new Newwwwww().start(stages);
           } catch (Exception ex) {
               Logger.getLogger(promo.class.getName()).log(Level.SEVERE, null, ex);
           }

       }
       
       }}
       
                                       

                                       

                                    }
                                });

                                JOptionPane.showConfirmDialog(null, kd);

                            }
                        });
                        JOptionPane.showConfirmDialog(null, nop);

                    }
                });
                ss.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK,true);
                        JRadioButton RB1=new JRadioButton("audio");
                         JRadioButton RB2=new JRadioButton("video");
                        JTextField tt=new JTextField();
                        ButtonGroup jgp=new ButtonGroup();
                        jgp.add(RB2);
                        jgp.add(RB1);
                        JComboBox tt1=new JComboBox();
                        JComboBox tt2=new JComboBox();
                        JComboBox tt3=new JComboBox();
                        JLabel tt4=new JLabel();
                        JButton tt5=new JButton("add url" );
                        JButton tt6=new JButton("add custom");
                        JButton tt7=new JButton("ADD TO SERVER");
                        JLabel tt8=new JLabel("artist name");
                        tt3.addItem("select the requirement below");/*, "hindi", "english");*/
                    tt3.addItem("hindi");
                    tt3.addItem("english");
                    tt2.addItem("select the requirement among below options");//, POP, Folk, Dance");
                    tt2.addItem("POP");
                    tt2.addItem("Folk");
                    tt2.addItem("Dance");
                    tt1.addItem("please select one among below");
RB1.setSelected(true);
                    Object[] ko={
                        "type",RB1,RB2,"song name",tt,tt8,tt1,"type",tt2,"LANGUAGE",tt3,tt4,tt5,tt6,tt7

                    };


                    //tt8.setVisible(false);
                    //tt1.setVisible(false);

                    tt6.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent ae) {
                            Statement t=null;
                            JComboBox ttk=new JComboBox();
                            JComboBox ttkk=new JComboBox();
                            ResultSet b=null;
                            String query="select * from singers";
                            JTextField singer=new JTextField();
                            //  JTextField language=new JTextField();
                            //  JTextField type=new JTextField();

                            // Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK);
                            Toolkit.getDefaultToolkit().setLockingKeyState(KeyEvent.VK_CAPS_LOCK, true);
                            int ii=tt3.getItemCount();
                            for(int ij=1;ij<=ii;++ij)
                            {
                                ttkk.addItem(tt3.getItemAt(ij-1));}

                            int iii=tt2.getItemCount();
                            for(int iij=1;iij<=iii;++iij)
                            {
                                ttk.addItem(tt2.getItemAt(iij-1));}
                            Object[] message={
                                "SINGER NAME",singer,"LANGUAGE",ttkk,"TYPE",ttk
                            };
                            JOptionPane.showConfirmDialog(null,message,"add more , more fun",JOptionPane.OK_CANCEL_OPTION);
                            String k=ttkk.getSelectedItem().toString();
                            String qw=ttk.getSelectedItem().toString();

                            String r=singer.getText();
                            try
                            {
                                Class.forName("com.mysql.jdbc.Driver");
                                Connection c=(Connection)
                                DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                                t=(Statement)c.createStatement();
                                b=t.executeQuery(query);

                                query="INSERT INTO singers (name,language,type) VALUES('"+(r)+"','"+(k)+"','"+qw+"');";
                                t.executeUpdate(query);

                            }catch (Exception i)
                            {JOptionPane.showMessageDialog(null,i.getMessage()); }

                        }
                    }

                );
                tt5.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {
                        if(RB1.isSelected())
{
                         f=new FileNameExtensionFilter("mp3 files", "MP3");
                       
}
else if(RB2.isSelected())
{
         f=new FileNameExtensionFilter("mp4 files", "MP4");
        
}

                        JFileChooser fc=new JFileChooser();
                      
                        fc.setFileFilter(f);
                        fc.setCurrentDirectory(new File("F:"));

                        fc.showOpenDialog(null);
                        String kbc;

                        kbc = fc.getSelectedFile().toURI().toString();
                        j=kbc;
                        tt4.setText(kbc+"");
                        //    System.err.println(kbc);

                    }
                });

                tt3.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {

                        Statement t1=null;
                        ResultSet b1=null;
                        String c1="select * from singers";
                        try
                        {
                            Class.forName("com.mysql.jdbc.Driver");
                            Connection c=(Connection)
                            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                            t1=(Statement)c.createStatement();

                            c1="Select name from singers where type='"+tt2.getSelectedItem().toString()+"' && language='"+tt3.getSelectedItem().toString()+"';";//
                            b1=t1.executeQuery(c1);
                            tt1.removeAllItems();
                            tt1.addItem("please select one among below");
                            while(b1.next())

                            {String f1=b1.getString(1);
                                tt1.addItem(f1);
                                //if(r.equals(f1))
                                //{
                                    //if(f2.equals(k))
                                    //query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
                                    //    t.executeUpdate(query);
                                    //this.setVisible(false);
                                    //new NewJFrame1().setVisible(true);
                                    //break;}
                            }

                            b1.close();
                            t1.close();
                            tt8.setVisible(true);
                            tt1.setVisible(true);

                        }catch(Exception i)
                        {JOptionPane.showMessageDialog(null,i.getMessage());}  }
                }
            );

            tt2.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {

                    Statement t1=null;
                    ResultSet b1=null;
                    String c1="select * from singers";
                    try
                    {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection c=(Connection)
                        DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                        t1=(Statement)c.createStatement();

                        c1="Select name from singers where type='"+tt2.getSelectedItem().toString()+"' && language='"+tt3.getSelectedItem().toString()+"';";//
                        b1=t1.executeQuery(c1);
                        tt1.removeAllItems();
                        tt1.addItem("please select one among below");
                        while(b1.next())

                        {String f1=b1.getString(1);
                            tt1.addItem(f1);
                            //if(r.equals(f1))
                            //{
                                //if(f2.equals(k))
                                //query="INSERT INTO login (USERNAME) VALUES('"+(r)+"');";
                                //    t.executeUpdate(query);
                                //this.setVisible(false);
                                //new NewJFrame1().setVisible(true);
                                //break;}
                        }

                        b1.close();
                        t1.close();
                        tt8.setVisible(true);
                        tt1.setVisible(true);

                    }catch(Exception i)
                    {JOptionPane.showMessageDialog(null,i.getMessage());}  }

            });
            tt7.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                                           
if(RB1.isSelected())
{
                        
                         quake="songs";
}
else if(RB2.isSelected())
{
        
         quake="video";
}
                    Statement a=null;
                    ResultSet b=null;
                    String query="select * from songs";

                    try
                    {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection c=(Connection)
                        DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
                        a=(Statement)c.createStatement();
                        b=a.executeQuery(query);

                        query="INSERT INTO "+quake+" (sname,aname,type,language,location) VALUES('"+tt.getText()+"','"+tt1.getSelectedItem().toString()+"','"+tt2.getSelectedItem().toString()+"','"+tt3.getSelectedItem().toString()+"','"+tt4.getText()+"');";
                        a.executeUpdate(query);

                        //   System.err.println("INSERT INTO songs (sname,aname,type,language,location) VALUES('"+tt.getText()+"','"+tt1.getSelectedItem().toString()+"','"+tt2.getSelectedItem().toString()+"','"+tt3.getSelectedItem().toString()+"','"+tt4.getText()+"');");

                    }catch (Exception i)
                    {JOptionPane.showMessageDialog(null,i.getMessage()); }

                }
            });

            JOptionPane.showConfirmDialog(null,ko);

        }});
        JOptionPane.showConfirmDialog(null,chios);

        }

        });

        JLabel k=new JLabel();
        Statement n1=null;
        ResultSet b=null;
        String k1=null;
        String query="select * from login";

        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/one_direction","root","anitaajay");
            n1=(Statement)c.createStatement();

            b=n1.executeQuery(query);
            b.next();
            k1=b.getString(1);

            b.close();
            n1.close();

        }catch(Exception i)
        {JOptionPane.showMessageDialog(null,"YOU HAVEN'T LOGIN");  }
        if(k1==null)
        {       System.exit(0);}
        else

        {
            k.setText("HI MASTER "+k1+"");

            Object ME[]={
                "",k,"",a1
            };

            JOptionPane.showConfirmDialog(this,ME);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new promo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
